---
apiVersion: v1
kind: Secret
metadata:
  name: osp-compute-0
  namespace: openshift-machine-api
data:
  password: cGFzc3dvcmQK
  username: YWRtaW4K
type: Opaque

---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name:     osp-compute-0
  namespace: openshift-machine-api
  labels:
    app: openstack
    workload: compute
spec:
  online: false
  bootMode: UEFI
  bootMACAddress: be:bb:cc:12:82:00
  hardwareProfile: libvirt
  bmc:
    address: 'ipmi://10.17.3.1:6230'
    credentialsName: osp-compute-0
    disableCertificateVerification: true

---
apiVersion: v1
kind: Secret
metadata:
  name: osp-compute-1
  namespace: openshift-machine-api
data:
  password: cGFzc3dvcmQK
  username: YWRtaW4K
type: Opaque

---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name:     osp-compute-1
  namespace: openshift-machine-api
  labels:
    app: openstack
    workload: compute
spec:
  online: false
  bootMode: UEFI
  bootMACAddress: be:bb:cc:12:82:01
  hardwareProfile: libvirt
  bmc:
    address: 'ipmi://10.17.3.1:6231'
    credentialsName: osp-compute-1
    disableCertificateVerification: true

---
apiVersion: v1
kind: Secret
metadata:
  name: osp-compute-2
  namespace: openshift-machine-api
data:
  password: cGFzc3dvcmQK
  username: YWRtaW4K
type: Opaque

---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name:     osp-compute-2
  namespace: openshift-machine-api
  labels:
    app: openstack
    workload: compute
spec:
  online: false
  bootMode: UEFI
  bootMACAddress: be:bb:cc:12:82:02
  hardwareProfile: libvirt
  bmc:
    address: 'ipmi://10.17.3.1:6232'
    credentialsName: osp-compute-2
    disableCertificateVerification: true
